# Simple script for removing harmonically bounded candidates from a VT generated by SPOT

import OTtools

filePath = None
defaultFile = './SPOT_Results.csv'

if not filePath:
    filePath = input('Choose a file: ')

if not filePath:
    filePath = defaultFile

system = OTtools.OTsystem.fromOTW(filePath)

optimized = system.getOptima()

optimized.toOTW('optimized_' + filePath)

print('done')
